[package]
name = "unlayer"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
lexopt = "0.3.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
tar = "0.4.44"
